# Generated by Django 4.1.6 on 2023-04-01 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(choices=[('STUDENT', 'Student'), ('PROFESSOR', 'Professor')], default='STUDENT', max_length=50)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dept_name', models.CharField(max_length=255)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_picture/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('app_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('joining_year', models.IntegerField()),
                ('designation', models.CharField(max_length=255)),
                ('cv', models.FileField(blank=True, null=True, upload_to='professor_cv/')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.app_user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('app_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('accademic_year', models.IntegerField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='student_cv/')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.app_user',),
        ),
    ]
