# Generated by Django 4.1.1 on 2023-03-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_Title', models.CharField(blank=True, max_length=30)),
                ('internship_Type', models.CharField(blank=True, max_length=10)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('stipend', models.IntegerField(blank=True, default=5000)),
                ('eligibility', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('no_Of_Openings', models.IntegerField(blank=True)),
                ('skills', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
